// @ts-check

import { writeFile } from "fs/promises";
import PackageJSON from "../package.json" assert { type: "json" };

/**
 * @param {string} name
 * @param {string} content
 */
const autogenerateFile = (name, content) =>
	writeFile(
		`./src/__autogenerated__/${name}.ts`,
		`// AUTOGENERATED. DO NOT MODIFY.

${content}`
	);

const numbers = PackageJSON.version.split(".");
autogenerateFile(
	"versionNumbers",
	`/**
 * @internal
 */
export const versionNumbers = ${JSON.stringify(numbers)};`
);
