name: Publish NPM package

on:
  push:
    branches:
      - "stable"
    tags:
      - "**"

  workflow_dispatch:

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: package

  publish-npm:
    name: Publish on NPM registry
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download package artifact
        uses: actions/download-artifact@v3
        with:
          name: package

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          registry: https://registry.npmjs.org/
          token: ${{ secrets.NPM_TOKEN }}

  publish-ghp:
    name: Publish on GitHub Packages registry
    needs: publish-npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download package artifact
        uses: actions/download-artifact@v3
        with:
          name: package

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          registry: https://npm.pkg.github.com/
          token: ${{ secrets.GITHUB_TOKEN }}
