name: Test with Jest

on:
  push:
    branches:
      - "master"
    tags:
      - "**"

  workflow_dispatch:

jobs:
  test:
    name: Test package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test
