name: Upload documentation

on:
  push:
    branches:
      - "stable"
    tags:
      - "**"
  workflow_dispatch:

jobs:
  build:
    name: Generate documentation
    runs-on: ubuntu-latest
    if: github.repository_owner == 'float-toolkit'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Generate documentation
        run: npm run docs

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs

  upload:
    name: Upload
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download documentation artifact
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: docs

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy

        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
